name: Virtual DSM
description: Run Virtual DSM on GitHub Actions
author: Synology Community

# Define your inputs here.
inputs:
  disk-size:
    description: "Disk size for Virtual DSM"
    required: false
    default: "1G"

# Define your outputs here.
outputs:
  port:
    description: Port number for Virtual DSM

runs:
  using: docker
  image: vdsm/virtual-dsm:7.14
  env:
    DISK_SIZE: ${{ inputs.who-to-greet }}
    DSM_PORT: ${{ steps.random-port.outputs.port }}
