name: Virtual DSM
description: Run Virtual DSM on GitHub Actions
author: Synology Community

# Define your inputs here.
inputs:
  disk-size:
    description: "Disk size for Virtual DSM"
    required: false
    default: "1G"
  port:
    description: "Port number for Virtual DSM"
    required: false
    default: "5000"

# Define your outputs here.
outputs:
  port:
    description: Port number for Virtual DSM

runs:
  using: docker
  image: ./Dockerfile
  # image: docker://vdsm/virtual-dsm:7.14

  env:
    DISK_SIZE: ${{ inputs.disk-size }}
    DSM_PORT: ${{ inputs.port }}
